DFE-Digital/get-into-teaching-frontend-tests

cypress/fixtures/expectedTestData.json
cypress/integration/HomePage-Smoke.spec.js
cypress/integration/MailinglistSignUpFlow-smoke.spec.js
cypress/support/PageObjectsMap/HomePage.js
cypress/support/commands.js

I've added smoke tests for GIT website home page.
Note: I've not fully implemented the  "Search for events" functionality . It's in progress..

Add smoke tests for homepage

---

cypress/integration/HomePage-Smoke.spec.js
cypress/support/pageobjects/Homepage.js

Add new test for search for an event functionality

Add test for search for an event functionality

---

package-lock.json
package.json

Upgrade lodash version to 4.17.19
Jira ticket - GITPB-475
https://dfedigital.atlassian.net/jira/software/projects/GITPB/boards/61?assignee=5e3295e56bd5c40ca395afc1&selectedIssue=GITPB-475

Upgrade lodash version to 4.17.19

---

.github/workflows/cypress.yml

Action added

---

cypress/fixtures/tta-signup-test-data.json
cypress/integration/teacher-training-adviser.spec.js
cypress/support/commands.js
cypress/support/pageobjects/TeacherTrainingAdviser.js
package.json

Add couple of cypress automated tests for tta flow

Add Cypress automated tests for TTA flow

---

cypress/integration/homepage-smoke.spec.js
cypress/support/commands.js
cypress/support/pageobjects/Homepage.js

Following are the changes related to home page screen-
1. update existing tests script
2. Add new tests
2. Remove content driven validation

Fix tests code and add new tests

---

.github/workflows/cypress-dev-passive.yml
.github/workflows/cypress-qa.yml
.github/workflows/cypress.yml
Dockerfile
README.md

Adding Docker file and executing build in pipeline

Adding Docker

---

cypress/integration/teacher-training-adviser.spec.js
cypress/support/commands.js

I've added following new tests scenario for tta flow
1. Privacy policy details check
2. sign up for non-returner candidate who has an equivalent qualification from another country
3. sign up for non-returner candidate who has an equivalent qualification from another country interested in primary stage teaching
4. sign up non-returner candidate who is studying for a degree

Add new tests for tta flow

---

cypress/integration/teacher-training-adviser.spec.js
cypress/support/commands.js

"Do you have a degree?" objects locator has been changed and same I've updated in tests script.

update tta flow objects locator

---

cypress/integration/teacher-training-adviser.spec.js

In order to increase test coverage, I've added below tests scenario. 
Sign up for non-returner who is studying for a degree and interested to teach in primary stage

Increase test coverage for tta flow

---

cypress/integration/event-signup-flow.spec.js
cypress/support/commands.js
cypress/support/pageobjects/EventSignupPage.js

In order to increase test coverage for event sign up flow, I've added couple of negative tests scenario.

Increase test coverage for event sign up flow

---

cypress/fixtures/tta-signup-test-data.json
cypress/integration/teacher-training-adviser.spec.js
cypress/support/commands.js

Add negative tests for Date of birth and telephone number field

Add negative tests scenario

---

cypress.json
cypress/integration/teacher-training-adviser.spec.js
cypress/support/commands.js
cypress/support/pageobjects/TeacherTrainingAdviser.js

The TTA journey has been refactored, which changed all of the form element IDs; this updates the selectors to match.

Update selectors to match the new TTA journey

---

cypress.json
cypress/fixtures/mailinglist-signup-test-data.json
cypress/integration/homepage-smoke.spec.js
cypress/integration/mailinglist-signup-flow.spec.js
cypress/integration/teacher-training-adviser.spec.js
cypress/support/commands.js

Update test scripts

---

cypress/integration/teacher-training-adviser.spec.js

Remove last two test due to cross origin error happening on page load

Remove last two test

---

cypress/integration/teacher-training-adviser.spec.js

Alter the existing tests as call-back feature has been changed

Update tests as per recent callback feature

---

README.md
cypress.json

alterations to make the readme a little more succinct, include some web links and commands for running in a recommended workflow.  plus a few missing instructions and installation/setup steps

tidy up the readme instructions

---

cypress/integration/event-signup-flow.spec.js
cypress/integration/homepage-smoke.spec.js

At the moment skip event sign up test as there is no event on test env

Skip event sign up test as there is no event on test env

---

cypress/integration/teacher-training-adviser.spec.js
cypress/support/commands.js

Removed the duplicate selectors.

Code refrctor/remove duplicate selectors

---

cypress/integration/teacher-training-adviser.spec.js
cypress/support/commands.js

Code refactoring

---

cypress/integration/mailinglist-signup-flow.spec.js
cypress/support/commands.js
cypress/support/pageobjects/MailinglistSignupPage.js

1. Remove telephone field from Mailing List wizard
2. Validate contact details on Mailing List completion page

Remove telephone field from Mailing List wizard

---

cypress/integration/teacher-training-adviser.spec.js
cypress/support/commands.js

Fix timeout issues

---

cypress/integration/mailinglist-signup-flow.spec.js
cypress/support/commands.js
cypress/support/pageobjects/MailinglistSignupPage.js

Validation for Privacy policy link

Add test for Privacy policy link

---

cypress/integration/teacher-training-adviser.spec.js

Validate "What is a GCSE?" link expands if user clicks on it

Add test for "What is a GCSE?" link expansion check

---

cypress.json
cypress/integration/teacher-training-adviser.spec.js

Validate feedback survey link if user clicks on feedback link

Add test for feedback link

---

cypress/integration/homepage-smoke.spec.js
cypress/support/pageobjects/Homepage.js
cypress/support/pageobjects/Navlinks.js

Social media link navigation check

Social media link navigation test

---

cypress/integration/teacher-training-adviser.spec.js

Remove only tag

---

cypress/integration/mailinglist-signup-flow.spec.js
cypress/support/commands.js

Update mailinglist tests

---

cypress/integration/homepage-smoke.spec.js

Fix timeout issue for YouTube page load

Fix timeout issue for YouTube page load

---

cypress/integration/mailinglist-signup-flow.spec.js
cypress/support/commands.js

1. "feedback on this website" link navigation check
2. hide feedback bar check

Feedback and hide link navigation check

---

cypress/integration/teacher-training-adviser.spec.js

"What did you think of this service?" link navigation check

"What did you think of this service?" link navigation check

---

cypress/integration/teacher-training-adviser.spec.js
cypress/support/commands.js
cypress/support/pageobjects/Navlinks.js

Hyperlink navigation(Scotland, Wales, Northern Ireland) validation

Hyperlink navigation(Scotland, Wales, Northern Ireland) check

---

cypress/support/pageobjects/Navlinks.js

Update link's href value

---

cypress/integration/homepage-smoke.spec.js

"Hide this message" link validation

"Hide this message" link validation

---

cypress/integration/mailinglist-signup-flow.spec.js

put wait time in between two consecutive login

Increase wait time

---

cypress/integration/teacher-training-adviser.spec.js
cypress/support/pageobjects/Homepage.js

1. Update selectors
2. Put wait in between two consecutive login

Test script update

---

.github/workflows/cypress.yml

Use matrix for specs

---

cypress/integration/teacher-training-adviser.spec.js

Update feedback page header property

Update feedback page header

---

cypress/integration/homepage-smoke.spec.js

Remove test skip tag

---

.github/workflows/cypress.yml

Add a task to just push out a simple message when all the matrix tasks have completed.

Run a post task after all matrix steps have completed

---

cypress/support/pageobjects/Homepage.js

Update banner text header property

Update banner text header selector

---

cypress/integration/mailinglist-signup-flow.spec.js
cypress/integration/teacher-training-adviser.spec.js

Increase waiting time in between two consecutive login

Increase waiting time in between two consecutive login

---

cypress/integration/event-signup-flow.spec.js
cypress/support/commands.js

Validate mobile field and displayed value

Validate mobile field and displayed value

---

cypress/fixtures/event-signup-test-data.json
cypress/fixtures/mailinglist-signup-test-data.json
cypress/integration/event-signup-flow.spec.js
cypress/support/commands.js

Use different email address for event signup user

Use different email address for event signup user

---

cypress/support/commands.js

Change class property ".search-for-events-no-results" to ".no-results"

Update class property

---

cypress/integration/mailinglist-signup-flow.spec.js
cypress/integration/teacher-training-adviser.spec.js
cypress/support/commands.js

Change step answers from a drop down to radio buttons

Change step answers from a drop down to radio buttons

---

cypress/integration/event-signup-flow.spec.js
cypress/support/commands.js

Test to check following pages load:-
1. Train to Teach Events
2. Online Events
3. School and University Events

Add page load tests

---

cypress/integration/event-signup-flow.spec.js

Removes double `//` where we should just have `/`

Remove double slashes

---

cypress/integration/event-signup-flow.spec.js
cypress/support/commands.js

Test to check page navigation for selected events

Increase test coverage for events category

---

cypress/integration/event-signup-flow.spec.js
cypress/support/commands.js

Search past online events

---

cypress/fixtures/event-signup-test-data.json
cypress/integration/event-signup-flow.spec.js

Change event type Train to Teach Events => Train to Teach events

Change events type

---

cypress/integration/event-signup-flow.spec.js

events category path update

---

cypress/integration/teacher-training-adviser.spec.js

Hyperlink navigation check on "Get support" page

Update tta flow tests

---

cypress/integration/teacher-training-adviser.spec.js
cypress/support/commands.js
cypress/support/pageobjects/Navlinks.js

External link response check

---

cypress/integration/teacher-training-adviser.spec.js

Change surname to last name

---

cypress/integration/teacher-training-adviser.spec.js
cypress/support/pageobjects/Navlinks.js

Validate feedback link

---

cypress/integration/non-regression-tests-suite/teacher-training-adviser.spec.js
cypress/integration/regression-tests-suite/teacher-training-adviser.spec.js

Segregate regression and non-regression tests of TTA flow based on high priority functionality.
**Note: teacher-training-adviser.spec file has been moved inside regression-tests-suite and non-regression-tests-suite folder.**

Segregate regression and non-regression tests

---

cypress/integration/non-regression-tests-suite/event-signup-flow.spec.js
cypress/integration/regression-tests-suite/event-signup-flow.spec.js
cypress/support/commands.js

Update CSS selectors

---

cypress/integration/non-regression-tests-suite/homepage.spec.js
cypress/support/pageobjects/Homepage.js
cypress/support/pageobjects/Navlinks.js

Link navigation check

---

cypress/integration/regression-tests-suite/event-signup-flow.spec.js
cypress/integration/regression-tests-suite/mailinglist-signup-flow.spec.js

Update Id selectors

---

cypress/integration/non-regression-tests-suite/event-signup-flow.spec.js
cypress/integration/regression-tests-suite/event-signup-flow.spec.js
cypress/support/commands.js

Remove Phone number (optional) validation

Remove Phone number (optional) validation

---

cypress/integration/regression-tests-suite/teacher-training-adviser.spec.js

Update Id selector for password field

Update Id selector for password field

---

.github/workflows/cypress.yml
cypress.json

Below environment variables need parameterization.
1. EVENT_USER_EMAIL_API_KEY
2. MAILING_LIST_USER_EMAIL_API_KEY
3. TTA_USER_EMAIL_API_KEY

Email api key parameterization

---

cypress/integration/non-regression-tests-suite/teacher-training-adviser.spec.js
cypress/support/commands.js

Below hyperlink navigation check on tta signup complete page
1. Online chat
2. Ways to train
3. Funding
4. Search for events

Hyperlink navigation check

---

cypress/integration/non-regression-tests-suite/event-signup-flow.spec.js

Update past online events page title

Update past online events page title

---

cypress/integration/regression-tests-suite/teacher-training-adviser.spec.js

Test Scenario - Allow mailing list sign up if already signed up for TTA

Update tta specs

---

cypress/integration/regression-tests-suite/homepage.spec.js

Remove **a day in the life of a teacher** link validation test

Update home page specs

---

.github/workflows/trello.yml

We use the code three times in different repositories, and we also might want to use the code in other projects. so we have decided to move it to a common repository
Github action [AddTrelloComment](https://github.com/DFE-Digital/github-actions/tree/master/AddTrelloComment) created
Does not effect application
Should not impact workflows

Create Trello Update

---

cypress/integration/non-regression-tests-suite/event-signup-flow.spec.js
cypress/integration/non-regression-tests-suite/mailinglist-signup-flow.spec.js
cypress/integration/non-regression-tests-suite/teacher-training-adviser.spec.js
cypress/integration/regression-tests-suite/teacher-training-adviser.spec.js
cypress/support/commands.js

Add email verification related specs in side non-regression pack

Add email verification related specs in side non-regression pack

---

cypress/integration/non-regression-tests-suite/homepage.spec.js

Home page - validate search icon functionality

Validate search icon functionality

---

cypress/integration/non-regression-tests-suite/event-signup-flow.spec.js
cypress/support/commands.js

Update test scenario **"It shows past events only"**

Fix past events specs

---

cypress/integration/regression-tests-suite/homepage.spec.js

Update link text

---

cypress/integration/visual-regression-tests-suite/homepage.spec.js

Home page - Increase visual regression tests coverage

Increase visual regression tests coverage

---

cypress/integration/regression-tests-suite/homepage.spec.js

Update link texts

---

.github/common_environment.yml
.github/workflows/build.yml

Create Docker image in Github Packages

GitHub packages

---

cypress/integration/non-regression-tests-suite/teacher-training-adviser.spec.js
cypress/support/commands.js

TTA tests update

---

cypress/integration/non-regression-tests-suite/teacher-training-adviser.spec.js
cypress/support/commands.js
cypress/support/pageobjects/EventSignupPage.js

This was recently renamed from `telephone` to `address-telephone`.

Update telephone selector

---

cypress/integration/non-regression-tests-suite/teacher-training-adviser.spec.js

Validate "Select a time zone" error message

Update test to validate error messages

---

cypress/integration/regression-tests-suite/teacher-training-adviser.spec.js

Add dial-in code to overseas telephone numbers, which is now required.

Fix overseas telephone numbers

---

cypress/support/commands.js

This changed to get around adblockers removing the button.

Update cookie acceptance id

---

cypress/integration/non-regression-tests-suite/teacher-training-adviser.spec.js
cypress/integration/regression-tests-suite/teacher-training-adviser.spec.js

Recent TTA copy changes broke some of the selectors in the TTA tests.

Update for recent TTA copy changes

---

cypress/integration/non-regression-tests-suite/event-signup-flow.spec.js
cypress/integration/regression-tests-suite/event-signup-flow.spec.js

We don't have any TTT events so these are failing.

Disable event tests

---

cypress/integration/non-regression-tests-suite/event-signup-flow.spec.js

We can't get to this page as there are no TTT events at the moment.

Disable sign up for event page check

---

cypress/integration/mailing_list.js

https://trello.com/c/t766rbnM
Add a test for the book a callback feature.
Also, set first name and last name in `beforeEach`

Add a test for the book a callback feature

---

cypress/integration/events.js
cypress/integration/mailing_list.js

The veriification code step has changed slightly and has updated copy; this udpates the relevant specs to match.

Update verification code steps with new copy

---

cypress/integration/get_an_adviser.js

This must have been a copy/paste error from a while ago.

Correct name of the TTA test suite

---

cypress/integration/mailing_list.js

The postcode field is now behind a yes/no radio input.

Update test for new mailing list postcode step

---

.github/workflows/cypress.yml
cypress/integration/get_an_adviser.js

Added Workflow Call

---

cypress/integration/get_an_adviser.js

In response to changes in the TTA verification code step.

Update verification code copy in TTA flow
